// Pipeline Jenkins pentru CI/CD al scriptului bash.
pipeline {
    agent any

    environment {
        IMAGE_NAME = "jbcristina/bash-deploy"
        DOCKER_CREDENTIALS_ID = "dockerhub-cred-id"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME -f docker/monitoring/Dockerfile .'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d --name bash-runner $IMAGE_NAME'
            }
        }
    }

    post {
        failure {
            echo '❌ Deploy eșuat. Verifică logurile.'
        }
    }
}