// Pipeline Jenkins pentru CI/CD al scriptului bash.
pipeline {
    agent any

    environment {
        IMAGE_NAME = "jbcristina/bash-deploy"
    }

    stages {
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME -f docker/monitoring/Dockerfile .'
            }
        }

        stage('Deploy') {
            steps {
                sh '''
                    docker rm -f bash-runner || true
                    ddocker run -d --name bash-runner $IMAGE_NAME
                '''
            }
        }
    }

    post {
        success {
            echo '✅ Deploy finalizat cu succes!'
        }
        failure {
            echo '❌ Deploy eșuat. Verifică logurile.'
        }
    }
}