// Pipeline Jenkins pentru CI/CD al scriptului python de backup.
pipeline {
    agent any

    environment {
        IMAGE_NAME = "jbcristina/backup"
        TAG = "latest"
        DOCKERHUB_CREDENTIALS = "dockerhub-cred-id"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Lint') {
            steps {
                sh '''
                    pip install flake8 --break-system-packages
                    ~/.local/bin/flake8 scripts/backup.py
                '''
            }
        }

        stage('Test') {
            steps {
                sh '''
                    pip install pytest --break-system-packages
                    export PATH=$PATH:~/.local/bin
                    pytest tests/test_backup.py
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t $IMAGE_NAME:$TAG -f docker/backup/Dockerfile .'
            }
        }
    }

    post {
        success {
            echo '✅ CI/CD pentru backup.py finalizat cu succes!'
        }
        failure {
            echo '❌ Eroare în pipeline. Verifică etapele.'
        }
    }
}